### ISSUE TITLE
Update photos and names of cabinet members 2024

### ISSUE THREAD

**Issue by ezhil56x** [cyscomvit/cyscom.github.io#52]
## Description

- Get the photos of current cabinet from the Dev Leads
- Convert them to webp for faster loading
- Move the old cabinet photos to `assets/images/cabinet/old` and add the current cabinet photos to `assets/images/cabinet`
- Follow this naming convention `2024-CabinetPosition-FirstnameLastname.webp` for all the photos
- Add 2023 cabinet to previous cabinet as below
![image](https://github.com/cyscomvit/cyscomvit.github.io/assets/103899034/712b53bc-5116-487e-89b6-d15a502dac2f)

https://github.com/cyscomvit/cyscomvit.github.io/blob/master/team.html

**Comment by Void-py** [comment]
@ezhil56x can you send the images of the current cabinet members
